<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pgae_fancycard"
 * Auto generated by Extension Builder 2021-03-31
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Fancy Card',
    'description' => 'A custom card element with fancy handling. It wil display an simple Card with an Image as Header and and Title and Subitle as Body. If you click on it it open a popup on large screens or an accordion body on smaller screens.',
    'category' => 'plugin',
    'author' => 'Patrik Garten',
    'author_email' => 'info@patrikgarten.de',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
